-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: tailor/swift/
    -   id: trailing-whitespace
        exclude: tailor/swift/
