-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: c2992bd3a11e3c0c2533ee370c26ac2b12d3a1b3
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: tailor/swift/
    -   id: trailing-whitespace
        exclude: tailor/swift/
