-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: cf550fcab3f12015f8676b8278b30e1a5bc10e70
    hooks:
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
        exclude: tailor/swift/
    -   id: end-of-file-fixer
        exclude: tailor/swift/
    -   id: flake8
        exclude: tailor/swift/
        args: [--max-line-length=120, --max-complexity=10]
    -   id: name-tests-test
    -   id: trailing-whitespace
        exclude: tailor/swift/
