-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: tailor/swift/
    -   id: trailing-whitespace
        exclude: tailor/swift/
