language: java
jdk:
  - oraclejdk8
before_install:
  - gem update bundler
  - pip install --user codecov
after_success:
  - codecov
  - ./gradlew coveralls
deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file:
    - build/distributions/tailor-*.tar
    - build/distributions/tailor-*.zip
  skip_cleanup: true
  on:
    tags: true
