name: Tailor
description: Static analyzer for Swift
domain_name: "http://tailor.sh"
github_url: "https://github.com/sleekbyte/tailor"

baseurl: "/"
exclude: [README.md, LICENSE.md, CNAME, Gemfile, Gemfile.lock, vendor]

sass:
  style: :compressed
