name: Tailor
company_name: Sleekbyte
company_url: "http://sleekbyte.com"
description: Static analyzer for Swift
github_url: "https://github.com/sleekbyte/tailor"

exclude: [README.md, LICENSE.md, CNAME, Gemfile, Gemfile.lock, vendor, script]

sass:
  style: :compressed
